[package]
name = "example"
version = "0.1.0"
edition = "2021"

[lib]
name = "example"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.5", features = [
    "extension-module",
    "auto-initialize",
] }
