from typing import Self


class Number:
    def __new__(cls, value: int) -> Self: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __hash__(self) -> int: ...

    def __bool__(self) -> bool: ...
